In [1]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.4.1
True


**Creating Tensors**

Create a tensor from existing data

In [2]:
# Converting List into 1D tensor

data = [2,1,1]
convert = torch.tensor(data)
print(convert)

tensor([2, 1, 1])


Create a tensor filled with zeros

In [3]:
zero = torch.zeros(3,4)
print(zero)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


Create a tensor filled with ones

In [4]:
one = torch.ones(2,3)
print(one)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


Create a tensor with random values between 0 and 1

In [5]:
# filled with random numbers uniformly sampled between 0 and 1.
random = torch.rand(2,3)
print(random)

tensor([[0.0290, 0.8043, 0.0487],
        [0.6586, 0.8061, 0.6677]])


Create an uninitialized tensor

In [6]:
notInitialliziedNow = torch.empty(2,4)
print(notInitialliziedNow)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])


Create a tensor with a range of values

In [7]:
tensor_arange = torch.arange(5,10)
print(tensor_arange)

tensor([5, 6, 7, 8, 9])


Create a tensor with linearly spaced values

In [8]:
tensor_linspace = torch.linspace(1,2,steps=5)
print(tensor_linspace)

tensor([1.0000, 1.2500, 1.5000, 1.7500, 2.0000])


Create an identity matrix

In [9]:
identity_matrix = torch.eye(3)
print(identity_matrix)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


**Basic Tensor Operations**

Reshaping Tensors

In [10]:
num = [1,2,3,4,5,6,7,8,9]
into_tensor = torch.tensor(num)

reshape = into_tensor.view(3,3)
print(reshape)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


Indexing

In [11]:
array = torch.tensor([[1,2,3],[4,5,6]])
print(array)

print("\nSpecific Element:",array[0,2])

print("\nFirst Row:",array[0,:])

tensor([[1, 2, 3],
        [4, 5, 6]])

Specific Element: tensor(3)

First Row: tensor([1, 2, 3])


Element-wise Operations

In [12]:
num1 = torch.tensor([[1,2,3],[4,5,6]])
num2 = torch.tensor([[7,8,9],[1,2,3]])

sum = torch.add(num1,num2)
print(sum)

mul = torch.mul(num1,num2)
print(mul)

tensor([[ 8, 10, 12],
        [ 5,  7,  9]])
tensor([[ 7, 16, 27],
        [ 4, 10, 18]])


Moving Tensors to GPU

In [13]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

torch_cpu = torch.tensor([[1,2,3],[4,5,6]])
gpu = torch_cpu.to(device)

print(gpu)

cpu = torch_cpu.to('cpu')
print(cpu)

cuda
tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0')
tensor([[1, 2, 3],
        [4, 5, 6]])


**Tensors**

In [14]:
import torch
import numpy as np

Tensors to NumPy Arrays

In [15]:
tensor_array = torch.tensor([1,2,3])
print(tensor_array)
convert = tensor_array.numpy()
print("Convert into numpy",convert)

# both are on cpu as tensor are not on cuda
print("\nChanging value\n")
tensor_array[1] = 1
print(tensor_array)
print(convert)

tensor([1, 2, 3])
Convert into numpy [1 2 3]

Changing value

tensor([1, 1, 3])
[1 1 3]


In [ ]:
# now let see what if we change the env of the tensor cpu to gpu

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

convert_tensor_cpu_to_gpu = tensor_array.to(device)
print(convert_tensor_cpu_to_gpu)

# checking if the array element is changes not
convert_tensor_cpu_to_gpu[1] = 2
print(convert_tensor_cpu_to_gpu)
print()
print(convert)

cuda
tensor([1, 1, 3], device='cuda:0')
tensor([1, 2, 3], device='cuda:0')

[1 1 3]


Convert the NumPy array to a PyTorch tensor

In [17]:
data = [2,1,1]

np_array = np.array(data)
print(np_array)

tensor = torch.from_numpy(np_array)
print(tensor)

[2 1 1]
tensor([2, 1, 1], dtype=torch.int32)


Attributes of a Tensor

In [18]:
print("Shape of tensor: ", tensor.shape)
print("Data Type of tensor: ", tensor.dtype)
print("Device tensor is stored on: ", tensor.device)

Shape of tensor:  torch.Size([3])
Data Type of tensor:  torch.int32
Device tensor is stored on:  cpu


In [19]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

In [20]:
print("Device tensor is stored on: ", tensor.device)

Device tensor is stored on:  cuda:0
